#!/usr/bin/env python3
"""
FinSight - Phase 14: end-to-end pipeline validation (read-only).

Walks all 21 checkpoints of the FinSight pipeline against the live stack and
writes a Component | Test | Expected | Actual | PASS/FAIL report to
docs/testing/E2E_REPORT.md.

    python scripts/validate_e2e.py               # full run + write report
    python scripts/validate_e2e.py --no-report   # console only
    python scripts/validate_e2e.py --section 6   # one checkpoint (1..21)

This script NEVER modifies the pipeline - it only inspects. Populate missing
outputs with scripts/run_e2e_pipeline.sh, then re-run.

Status: PASS ok · FAIL real defect · BLOCKED upstream output missing (run the
job) · WARN works but degraded (e.g. synthetic-data quirk). Exit 0 iff no FAIL.
"""
from __future__ import annotations

import argparse
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
NN = "finsight-namenode"
HS2 = "finsight-hiveserver2"
MONGO = "finsight-mongodb"
KAFKA = "finsight-kafka"
CONNECT_URL = "http://localhost:8083"
NEO4J_URI = "bolt://localhost:7687"

_ENV: dict[str, str] = {}
for _line in (REPO / ".env").read_text().splitlines() if (REPO / ".env").exists() else []:
    _line = _line.strip()
    if _line and not _line.startswith("#") and "=" in _line:
        k, v = _line.split("=", 1)
        _ENV[k] = v

NEO4J_PW = _ENV.get("NEO4J_PASSWORD", "")
MONGO_URI = (f"mongodb://{_ENV.get('MONGO_INITDB_ROOT_USERNAME', 'finsight_admin')}:"
             f"{_ENV.get('MONGO_INITDB_ROOT_PASSWORD', '')}@localhost:27017/"
             f"{_ENV.get('MONGO_DB', 'finsight')}?authSource=admin")
_NOISE = ("SLF4J", "log4j", "WARNING", "Picked up", "Connecting to", "Connected to",
          "Closing:", "Beeline", "Transaction isolation", "No such file", "WARN ")


# --------------------------------------------------------------------------- #
class Report:
    def __init__(self) -> None:
        self.rows: list[dict] = []

    def add(self, component: str, test: str, expected: str, actual: str,
            status: str) -> None:
        self.rows.append(dict(component=component, test=test, expected=expected,
                              actual=str(actual)[:220], status=status))
        mark = {"PASS": "PASS", "FAIL": "FAIL", "BLOCKED": "BLKD", "WARN": "WARN",
                "SKIP": "SKIP"}[status]
        print(f"  [{mark}] {component:<22} {test}")
        if status in ("FAIL", "BLOCKED", "WARN"):
            print(f"         expected: {expected}")
            print(f"         actual  : {actual}")

    def counts(self) -> dict:
        c = {k: 0 for k in ("PASS", "FAIL", "BLOCKED", "WARN", "SKIP")}
        for r in self.rows:
            c[r["status"]] += 1
        return c

    def write_md(self, path: Path) -> None:
        c = self.counts()
        lines = [
            "# FinSight — End-to-End Validation Report",
            "",
            f"_Generated by `scripts/validate_e2e.py` — {_now()}_",
            "",
            f"**Total {len(self.rows)} · PASS {c['PASS']} · FAIL {c['FAIL']} · "
            f"BLOCKED {c['BLOCKED']} · WARN {c['WARN']} · SKIP {c['SKIP']}**",
            "",
            "## Pipeline flows",
            "",
            "| Flow | Checkpoints | Worst status |",
            "|---|---|---|",
        ]
        flows = [
            ("Transactions.csv → Producer → txn-raw → Fraud Streaming → txn-flagged",
             ("1 ", "2 ", "6 ", "7 ")),
            ("txn-raw → Kafka Connect → HDFS → Parquet → Hive → Spark SQL",
             ("3 ", "4 ", "5 ", "12 ", "13 ", "14 ", "15 ", "16 ", "17 ")),
            ("HDFS → Risk Scoring → risk_scores", ("10 ",)),
            ("HDFS → CLV Scoring → clv_scores", ("11 ",)),
            ("txn-raw → Churn Streaming → txn-churn / churn_alerts", ("8 ", "9 ")),
            ("MongoDB → Customer Profiles", ("18 ",)),
            ("Neo4j → Fraud Graph → Fraud Ring Detection", ("19 ",)),
            ("Hive + MongoDB + Spark → Alteryx → Power BI", ("20 ", "21 ")),
        ]
        order = {"FAIL": 0, "BLOCKED": 1, "WARN": 2, "SKIP": 3, "PASS": 4}
        for label, prefixes in flows:
            sts = [row["status"] for row in self.rows
                   if any(row["component"].startswith(p) for p in prefixes)]
            worst = min(sts, key=lambda s: order[s]) if sts else "SKIP"
            lines.append(f"| {label} | {', '.join(p.strip() for p in prefixes)} | {worst} |")
        lines += [
            "",
            "## Checkpoint detail",
            "",
            "| Component | Test | Expected | Actual | Status |",
            "|---|---|---|---|---|",
        ]
        for r in self.rows:
            esc = lambda s: str(s).replace("|", "\\|").replace("\n", " ")
            lines.append(f"| {esc(r['component'])} | {esc(r['test'])} | "
                         f"{esc(r['expected'])} | {esc(r['actual'])} | {r['status']} |")
        lines += ["", "## Legend", "",
                  "- **PASS** — checkpoint verified.",
                  "- **FAIL** — a real defect; investigate before any change.",
                  "- **BLOCKED** — upstream output not present; run the named job "
                  "(`scripts/run_e2e_pipeline.sh`) then re-validate.",
                  "- **WARN** — works but degraded (usually a synthetic-data quirk, "
                  "documented in `docs/testing/known-issues.md`).", ""]
        path.write_text("\n".join(lines), encoding="utf-8")


def _now() -> str:
    import datetime as _d
    return _d.datetime.now(_d.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


# --------------------------------------------------------------------------- #
def sh(*cmd, timeout=240, stdin=None):
    return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout,
                          input=stdin, cwd=REPO)


def docker_running(name: str) -> bool:
    r = sh("docker", "inspect", "-f", "{{.State.Running}}", name)
    return r.stdout.strip() == "true"


def http_get(url: str, timeout=8):
    import urllib.request
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            return resp.status, resp.read().decode("utf-8", "replace")
    except Exception as exc:  # noqa: BLE001
        return None, str(exc)


def hive(sql: str):
    r = sh("docker", "exec", HS2, "beeline", "-u",
           "jdbc:hive2://localhost:10000/finsight", "--silent=true",
           "--showHeader=true", "--outputformat=csv2", "-e", sql)
    lines = [l for l in r.stdout.splitlines()
             if l.strip() and not any(n in l for n in _NOISE)]
    return lines, (r.stdout + r.stderr)


def hive_scalar(sql: str):
    lines, raw = hive(sql)
    if len(lines) >= 2:
        try:
            return float(lines[1].split(",")[0])
        except ValueError:
            return lines[1].split(",")[0]
    return None


def mongo_eval(js: str):
    r = sh("docker", "exec", MONGO, "mongosh", MONGO_URI, "--quiet", "--eval",
           f"print(JSON.stringify(({js})))")
    for ln in reversed([l for l in r.stdout.splitlines() if l.strip()]):
        try:
            return json.loads(ln)
        except json.JSONDecodeError:
            continue
    return None


def neo4j_scalar(cypher: str):
    try:
        from neo4j import GraphDatabase
    except ModuleNotFoundError:
        return None
    try:
        d = GraphDatabase.driver(NEO4J_URI, auth=("neo4j", NEO4J_PW))
        with d.session() as s:
            rec = s.run(cypher).single()
        d.close()
        return rec[0] if rec else None
    except Exception:  # noqa: BLE001
        return None


def hdfs_test(path: str, flag="-e") -> bool:
    return sh("docker", "exec", NN, "hdfs", "dfs", "-test", flag, path).returncode == 0


def hdfs_ls(path: str) -> list[str]:
    r = sh("docker", "exec", NN, "hdfs", "dfs", "-ls", path)
    return [l.split()[-1] for l in r.stdout.splitlines() if l.startswith(("d", "-"))]


def kafka_offsets(topic: str):
    r = sh("docker", "exec", KAFKA, "kafka-run-class",
           "kafka.tools.GetOffsetShell", "--broker-list", "kafka:29092",
           "--topic", topic)
    parts, total = [], 0
    for ln in r.stdout.splitlines():
        m = re.match(rf"{re.escape(topic)}:(\d+):(\d+)", ln.strip())
        if m:
            parts.append(int(m.group(1)))
            total += int(m.group(2))
    return (len(parts), total) if parts else (None, None)


def read_parquet_dir(hdfs_dir: str):
    """-> (pyarrow schema names list, row count) or (None, None)."""
    try:
        import pyarrow.parquet as pq
    except ModuleNotFoundError:
        return None, None
    if not hdfs_test(hdfs_dir):
        return None, None
    entries = hdfs_ls(hdfs_dir)
    files = [f for f in entries if f.endswith(".parquet")]
    # one level of Hive-style partition dirs (e.g. alert_date=2023-01-08/)
    for d in entries:
        if "=" in Path(d).name and "." not in Path(d).name:
            files += [f for f in hdfs_ls(d) if f.endswith(".parquet")]
    if not files:
        return None, None
    tmp = Path(tempfile.mkdtemp())
    try:
        cols, rows = None, 0
        for f in files[:20]:
            local = tmp / Path(f).name
            if sh("docker", "exec", NN, "hdfs", "dfs", "-get", "-f", f,
                  f"/tmp/{local.name}").returncode:
                continue
            sh("docker", "cp", f"{NN}:/tmp/{local.name}", str(local))
            sh("docker", "exec", NN, "rm", "-f", f"/tmp/{local.name}")
            if not local.exists():
                continue
            t = pq.read_table(local)
            cols = list(t.schema.names) if cols is None else cols
            rows += t.num_rows
        return cols, rows
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def csv_header(path: Path) -> list[str]:
    if not path.is_file():
        return []
    with path.open(encoding="utf-8") as fh:
        return fh.readline().strip().split(",")


def csv_rows(path: Path) -> int:
    if not path.is_file():
        return 0
    with path.open(encoding="utf-8") as fh:
        return max(0, sum(1 for _ in fh) - 1)


# --------------------------------------------------------------------------- #
def sec_01_kafka(r: Report):
    up = docker_running(KAFKA)
    r.add("1 Kafka", "broker container running", "running", up, "PASS" if up else "FAIL")
    rr = sh("docker", "exec", KAFKA, "kafka-topics", "--bootstrap-server",
            "kafka:29092", "--list")
    topics = set(rr.stdout.split())
    want = {"txn-raw", "txn-flagged", "txn-churn"}
    ok = want <= topics
    r.add("1 Kafka", "core topics exist", "txn-raw, txn-flagged, txn-churn",
          sorted(want & topics), "PASS" if ok else "FAIL")


def sec_02_txn_raw(r: Report):
    nparts, total = kafka_offsets("txn-raw")
    r.add("2 txn-raw", "partition count", "3", nparts,
          "PASS" if nparts == 3 else "FAIL" if nparts else "FAIL")
    r.add("2 txn-raw", "messages produced", ">= 100", total,
          "PASS" if (total or 0) >= 100 else "BLOCKED")


def sec_03_connect(r: Report):
    st, body = http_get(f"{CONNECT_URL}/connectors")
    r.add("3 Kafka Connect", "REST reachable", "HTTP 200", st,
          "PASS" if st == 200 else "FAIL")
    st, body = http_get(f"{CONNECT_URL}/connectors/finsight-hdfs-sink-txn-raw/status")
    running = False
    if st == 200:
        j = json.loads(body)
        running = (j["connector"]["state"] == "RUNNING"
                   and all(t["state"] == "RUNNING" for t in j["tasks"]))
    r.add("3 Kafka Connect", "hdfs-sink connector + tasks RUNNING", "RUNNING",
          body[:120] if st == 200 else st, "PASS" if running else "FAIL")


def sec_04_hdfs(r: Report):
    st, _ = http_get("http://localhost:9870/dfshealth.html")
    r.add("4 HDFS", "NameNode UI reachable", "HTTP 200", st,
          "PASS" if st == 200 else "FAIL")
    for d in ("/finsight/raw", "/finsight/processed", "/finsight/checkpoints",
              "/finsight/exports"):
        ok = hdfs_test(d)
        r.add("4 HDFS", f"dir {d}", "exists", ok, "PASS" if ok else "FAIL")


def sec_05_parquet(r: Report):
    base = "/finsight/raw/txn-raw"
    ok = hdfs_test(base)
    steps = [d for d in hdfs_ls(base) if "/step=" in d] if ok else []
    r.add("5 Parquet", "raw landing partitioned by step", ">= 1 step=* dir",
          f"{len(steps)} step dirs", "PASS" if steps else "BLOCKED")
    cols, rows = read_parquet_dir(f"{base}/step=1") if steps else (None, None)
    want = {"step", "type", "amount", "nameOrig", "isFraud"}
    schema_ok = cols is not None and want <= set(cols)
    r.add("5 Parquet", "raw parquet schema", "has step,type,amount,nameOrig,isFraud",
          cols, "PASS" if schema_ok else "BLOCKED" if cols is None else "FAIL")


def sec_06_fraud_stream(r: Report):
    m = "/finsight/processed/streaming_metrics"
    if not hdfs_test(m):
        r.add("6 Fraud Streaming", "streaming_metrics written", "HDFS dir with JSON",
              "missing", "BLOCKED")
        return
    r_ = sh("docker", "exec", NN, "bash", "-lc", f"hdfs dfs -cat {m}/* 2>/dev/null")
    recs = [json.loads(l) for l in r_.stdout.splitlines() if l.strip().startswith("{")]
    r.add("6 Fraud Streaming", "micro-batch metrics rows", ">= 1",
          len(recs), "PASS" if recs else "BLOCKED")
    if recs:
        keys = set(recs[0])
        want = {"total_count", "flagged_count", "fraud_rate_pct"}
        r.add("6 Fraud Streaming", "metrics schema", "total/flagged/fraud_rate_pct",
              sorted(keys & want), "PASS" if want <= keys else "FAIL")
        tot = sum(x.get("total_count", 0) for x in recs)
        fl = sum(x.get("flagged_count", 0) for x in recs)
        rate = 100 * fl / tot if tot else 0
        r.add("6 Fraud Streaming", "fraud rate sane", "0 <= rate <= 100",
              f"{rate:.2f}% ({fl}/{tot})", "PASS" if 0 <= rate <= 100 else "FAIL")


def sec_07_txn_flagged(r: Report):
    nparts, total = kafka_offsets("txn-flagged")
    r.add("7 txn-flagged", "topic exists", "1 partition", nparts,
          "PASS" if nparts is not None else "FAIL")
    r.add("7 txn-flagged", "flagged messages present", ">= 0 (rule-dependent)",
          total, "PASS" if total is not None else "FAIL")
    # business rule check on the flagged bridge output, if present
    fl = REPO / "powerbi" / "exports" / "flagged_transactions.csv"
    if fl.is_file() and csv_rows(fl) > 0:
        import csv as _csv
        bad = 0
        with fl.open(encoding="utf-8") as fh:
            for row in _csv.DictReader(fh):
                if not (row["type"] in ("TRANSFER", "CASH_OUT")
                        and float(row["amount"]) > 200000
                        and float(row["newbalanceDest"]) == 0):
                    bad += 1
        r.add("7 txn-flagged", "every flagged row obeys fraud rule",
              "0 violations", f"{bad} violations", "PASS" if bad == 0 else "FAIL")
    else:
        r.add("7 txn-flagged", "fraud-rule spot check", "flagged rows available",
              "no bridge output", "BLOCKED")


def sec_08_churn_stream(r: Report):
    a = "/finsight/processed/churn_alerts"
    ok = hdfs_test(a)
    cols, rows = read_parquet_dir(a) if ok else (None, None)
    if rows:
        status, actual = "PASS", f"{rows} rows"
    elif ok:
        status, actual = "WARN", ("dir created, 0 alerts — expected on the "
                                  "synthetic 1-txn/customer data (KI-2)")
    else:
        status, actual = "BLOCKED", "missing — run spark/streaming/run_churn_detection.sh --once"
    r.add("8 Churn Streaming", "churn_alerts written", "HDFS dir (rows on real data)",
          actual, status)
    if cols:
        want = {"customerId", "signals", "signal_count"}
        r.add("8 Churn Streaming", "churn_alerts schema",
              "customerId, signals, signal_count", cols,
              "PASS" if want <= set(cols) else "WARN")


def sec_09_txn_churn(r: Report):
    nparts, total = kafka_offsets("txn-churn")
    r.add("9 txn-churn", "topic exists", "1 partition", nparts,
          "PASS" if nparts is not None else "FAIL")
    r.add("9 txn-churn", "churn alert messages", ">= 0", total,
          "PASS" if total is not None else "FAIL")


def sec_10_risk(r: Report):
    cols, rows = read_parquet_dir("/finsight/processed/risk_scores")
    r.add("10 Risk Scoring", "risk_scores output", "HDFS parquet with rows",
          f"{rows} rows" if rows else "missing", "PASS" if rows else "BLOCKED")
    if cols:
        want = {"customerId", "risk_score", "risk_tier"}
        r.add("10 Risk Scoring", "risk_scores schema",
              "customerId, risk_score, risk_tier", cols,
              "PASS" if want <= set(cols) else "FAIL")


def sec_11_clv(r: Report):
    cols, rows = read_parquet_dir("/finsight/processed/clv_scores")
    r.add("11 CLV Scoring", "clv_scores output", "HDFS parquet with rows",
          f"{rows} rows" if rows else "missing", "PASS" if rows else "BLOCKED")
    if cols:
        want = {"customerId", "clv_score", "clv_classification"}
        r.add("11 CLV Scoring", "clv_scores schema",
              "customerId, clv_score, clv_classification", cols,
              "PASS" if want <= set(cols) else "FAIL")
        r.add("11 CLV Scoring", "row count reasonable", "100 .. 20000",
              rows, "PASS" if 100 <= rows <= 20000 else "WARN")


def _hive_table(name: str) -> bool:
    lines, _ = hive(f"SHOW TABLES LIKE '{name}'")
    return any(name in l for l in lines)


def sec_12_hive_txn(r: Report):
    ok = _hive_table("transactions")
    r.add("12 Hive transactions", "table exists", "finsight.transactions", ok,
          "PASS" if ok else "FAIL")
    if ok:
        lines, _ = hive("DESCRIBE transactions")
        cols = {l.split(",")[0].strip().lower() for l in lines[1:]}
        want = {"step", "type", "amount", "nameorig", "isfraud", "isflaggedfraud"}
        r.add("12 Hive transactions", "schema", "13 cols incl step,type,amount,isFraud",
              f"{len(cols)} cols", "PASS" if want <= cols else "FAIL")
        n = hive_scalar("SELECT COUNT(*) FROM transactions")
        note = "" if (n or 0) >= 100 else "  (KI-1: HiveServer2/Tez aggregation returns 0; Spark reads it fine)"
        r.add("12 Hive transactions", "record count reasonable", ">= 100",
              f"{n}{note}", "PASS" if (n or 0) >= 100 else "WARN")


def sec_13_hive_fraud_view(r: Report):
    ok = _hive_table("vw_fraud_transactions")
    r.add("13 Hive fraud view", "view exists", "finsight.vw_fraud_transactions", ok,
          "PASS" if ok else "FAIL")
    if ok:
        v = hive_scalar("SELECT COUNT(*) FROM vw_fraud_transactions")
        b = hive_scalar("SELECT COUNT(*) FROM transactions WHERE isFraud = 1")
        if v == b and (v or 0) > 0:
            status = "PASS"
        elif v == b:
            status = "WARN"   # both 0 - HiveServer2/Tez aggregation issue (KI-1)
        else:
            status = "FAIL"
        r.add("13 Hive fraud view", "view == transactions WHERE isFraud=1",
              "equal and > 0", f"view={v} base={b}"
              + ("  (KI-1: Hive aggregation returns 0)" if status == "WARN" else ""),
              status)


def sec_14_hive_mart(r: Report):
    ok = _hive_table("txn_summary_mart")
    r.add("14 Hive summary mart", "table exists", "finsight.txn_summary_mart", ok,
          "PASS" if ok else "FAIL")
    if ok:
        lines, _ = hive("DESCRIBE txn_summary_mart")
        cols = {l.split(",")[0].strip().lower() for l in lines[1:]}
        want = {"customerid", "step", "txn_count", "total_amount", "fraud_count",
                "txn_types", "last_balance"}
        r.add("14 Hive summary mart", "schema (9 spec fields)",
              "customerId,step,txn_count,total_amount,...", f"{len(cols)} cols",
              "PASS" if want <= cols else "FAIL")


def sec_15_compliance(r: Report):
    if _hive_table("compliance_summary"):
        n = hive_scalar("SELECT COUNT(*) FROM compliance_summary")
        src = "hive table"
    else:
        cols, n = read_parquet_dir("/finsight/processed/compliance_summary")
        src = "hdfs parquet"
    r.add("15 Spark SQL compliance", "compliance_summary output",
          "per-type rows (<= 5)", f"{n} rows ({src})" if n else "missing",
          "PASS" if n and n <= 5 else "BLOCKED" if not n else "WARN")


def sec_16_cust_fraud(r: Report):
    ok = _hive_table("customer_fraud_summary")
    cols, rows = read_parquet_dir("/finsight/processed/customer_fraud_summary")
    r.add("16 Customer fraud summary", "output present",
          "Hive table + HDFS parquet", f"table={ok} rows={rows}",
          "PASS" if (ok and rows) else "BLOCKED")
    if cols:
        want = {"customerId", "total_transactions", "confirmed_fraud_count",
                "fraud_rate_pct"}
        r.add("16 Customer fraud summary", "schema",
              "customerId,total_transactions,confirmed_fraud_count,fraud_rate_pct",
              cols, "PASS" if want <= set(cols) else "FAIL")


def sec_17_dormancy(r: Report):
    cols, rows = read_parquet_dir("/finsight/processed/dormancy_report")
    csv_ok = hdfs_test("/finsight/exports/dormancy_report.csv")
    r.add("17 Dormancy", "dormancy_report output", "HDFS parquet (+ CSV export)",
          f"parquet={rows} csv={csv_ok}", "PASS" if rows is not None else "BLOCKED")
    if cols:
        want = {"customerId", "steps_inactive", "dormancy_severity"}
        r.add("17 Dormancy", "schema", "customerId,steps_inactive,dormancy_severity",
              cols, "PASS" if want <= set(cols) else "FAIL")


def sec_18_mongo(r: Report):
    up = docker_running(MONGO)
    r.add("18 MongoDB", "container running", "running", up, "PASS" if up else "FAIL")
    n = mongo_eval('db.getSiblingDB("finsight").customers.countDocuments({})')
    r.add("18 MongoDB", "customers count", "10000", n,
          "PASS" if n == 10000 else "WARN" if n else "FAIL")
    idx = mongo_eval('db.getSiblingDB("finsight").customers.getIndexes()') or []
    keys = [list(i.get("key", {}).keys()) for i in idx]
    compound = ["customerId", "segment"] in keys
    r.add("18 MongoDB", "compound index {customerId, segment}", "present",
          compound, "PASS" if compound else "FAIL")
    segs = mongo_eval('db.getSiblingDB("finsight").customers.distinct("segment")') or []
    want = {"Premium", "Standard", "Basic", "Private Banking", "Student"}
    r.add("18 MongoDB", "segment values", "the 5 spec segments",
          sorted(segs), "PASS" if want == set(segs) else "FAIL")


def sec_19_neo4j(r: Report):
    up = docker_running("finsight-neo4j")
    r.add("19 Neo4j", "container running", "running", up, "PASS" if up else "FAIL")
    acc = neo4j_scalar("MATCH (a:Account) RETURN count(a)")
    txn = neo4j_scalar("MATCH (t:Transaction) RETURN count(t)")
    sent = neo4j_scalar("MATCH ()-[r:SENT]->() RETURN count(r)")
    recv = neo4j_scalar("MATCH ()-[r:RECEIVED_BY]->() RETURN count(r)")
    r.add("19 Neo4j", "Account nodes", ">= 1", acc, "PASS" if (acc or 0) > 0 else "BLOCKED")
    r.add("19 Neo4j", "Transaction nodes", ">= 1", txn, "PASS" if (txn or 0) > 0 else "BLOCKED")
    r.add("19 Neo4j", "SENT relationships", ">= 1", sent, "PASS" if (sent or 0) > 0 else "BLOCKED")
    r.add("19 Neo4j", "RECEIVED_BY relationships", ">= 1", recv,
          "PASS" if (recv or 0) > 0 else "BLOCKED")
    ring = neo4j_scalar(
        "MATCH (s:Account)-[:SENT]->(:Transaction)-[:RECEIVED_BY]->(rx:Account) "
        "WITH rx, count(DISTINCT s) AS n WHERE n > 3 RETURN count(rx)")
    r.add("19 Neo4j", "fraud-ring query (> 3 distinct senders)", ">= 0 accounts",
          ring, "PASS" if ring is not None else "BLOCKED")


def sec_20_alteryx(r: Report):
    out = REPO / "alteryx" / "outputs"
    b = out / "customer_risk_blend.csv"
    t = out / "transaction_summary.csv"
    r.add("20 Alteryx outputs", "customer_risk_blend present",
          "alteryx/outputs/customer_risk_blend.(xlsx|csv)",
          f"{csv_rows(b)} rows" if b.is_file() else "missing",
          "PASS" if csv_rows(b) > 0 else "BLOCKED")
    if b.is_file():
        want = {"customerId", "composite_risk_score", "fraud_rate_pct",
                "churn_probability"}
        h = set(csv_header(b))
        r.add("20 Alteryx outputs", "customer_risk_blend schema",
              "customerId, composite_risk_score, fraud_rate_pct, churn_probability",
              sorted(h & want), "PASS" if want <= h else "FAIL")
    r.add("20 Alteryx outputs", "transaction_summary present",
          "alteryx/outputs/transaction_summary.csv",
          f"{csv_rows(t)} rows" if t.is_file() else "missing",
          "PASS" if csv_rows(t) > 0 else "BLOCKED")
    if t.is_file():
        want = {"transaction_type", "step", "total_volume", "fraud_count"}
        h = set(csv_header(t))
        r.add("20 Alteryx outputs", "transaction_summary schema",
              "transaction_type, step, total_volume, fraud_count", sorted(h & want),
              "PASS" if want <= h else "FAIL")


def sec_21_powerbi(r: Report):
    ex = REPO / "powerbi" / "exports"
    required = {
        "dim_date.csv": {"step", "event_ts", "date"},
        "dim_transaction_type.csv": {"transaction_type"},
        "dim_customer.csv": {"customerId", "segment", "churn_probability"},
        "customer_products.csv": {"customerId", "product"},
        "transaction_summary.csv": {"transaction_type", "step", "total_volume"},
    }
    for fname, want in required.items():
        p = ex / fname
        n = csv_rows(p)
        h = set(csv_header(p))
        status = "PASS" if (n > 0 and want <= h) else "BLOCKED" if n == 0 else "FAIL"
        r.add("21 Power BI datasets", f"{fname}",
              f"exists, {sorted(want)}", f"{n} rows, cols {sorted(h)[:6]}", status)
    for opt in ("compliance_summary.csv", "dormancy_report.csv",
                "streaming_metrics.csv", "flagged_transactions.csv",
                "daily_summary.csv"):
        p = ex / opt
        r.add("21 Power BI datasets", f"{opt} (optional)", "built by export_datasets.py",
              f"{csv_rows(p)} rows" if p.is_file() else "not built",
              "PASS" if p.is_file() and csv_rows(p) >= 0 else "BLOCKED")


# --------------------------------------------------------------------------- #
def sec_cross_cutting(r: Report):
    # -- no secrets committed --
    tracked = sh("git", "-C", str(REPO), "ls-files").stdout.splitlines()
    env_tracked = [f for f in tracked if f == ".env" or f.endswith("/.env")]
    r.add("X Secrets", ".env not tracked", "0 tracked .env files",
          env_tracked or "none", "PASS" if not env_tracked else "FAIL")
    key_files = [f for f in tracked if f.endswith((".pem", ".key", ".p12", ".pfx"))]
    r.add("X Secrets", "no private-key files tracked", "0", key_files or "none",
          "PASS" if not key_files else "FAIL")
    grep = sh("git", "-C", str(REPO), "grep", "-nI", "-E",
              r"CHANGE_ME_[a-z_]+_pw\s*=\s*\S|BEGIN (RSA|OPENSSH|PRIVATE)",
              "--", ":!*.md", ":!.env.example")
    hits = [l for l in grep.stdout.splitlines() if l.strip()]
    r.add("X Secrets", "no real credentials in tracked source", "0 hits",
          hits[:3] or "none", "PASS" if not hits else "FAIL")

    # -- no large datasets committed --
    big = []
    for f in tracked:
        p = REPO / f
        if p.is_file() and p.stat().st_size > 5_000_000:
            big.append(f"{f} ({p.stat().st_size // 1024}KB)")
    r.add("X Large files", "no tracked file > 5 MB", "0", big or "none",
          "PASS" if not big else "FAIL")
    data_ext = [f for f in tracked
                if f.endswith((".parquet", ".avro"))
                or (f.endswith(".csv") and not f.startswith("tests/"))]
    r.add("X Large files", "no dataset files tracked (.parquet/.csv/.avro)", "0",
          data_ext or "none", "PASS" if not data_ext else "FAIL")

    # -- services reachable --
    for name in ("finsight-kafka", "finsight-kafka-connect", "finsight-namenode",
                 "finsight-datanode", "finsight-spark-master", "finsight-spark-worker",
                 "finsight-hive-metastore", "finsight-hiveserver2", "finsight-mongodb",
                 "finsight-neo4j", "finsight-hive-postgres"):
        up = docker_running(name)
        r.add("X Services", name, "running", up, "PASS" if up else "FAIL")


_SECTIONS = [
    sec_01_kafka, sec_02_txn_raw, sec_03_connect, sec_04_hdfs, sec_05_parquet,
    sec_06_fraud_stream, sec_07_txn_flagged, sec_08_churn_stream, sec_09_txn_churn,
    sec_10_risk, sec_11_clv, sec_12_hive_txn, sec_13_hive_fraud_view, sec_14_hive_mart,
    sec_15_compliance, sec_16_cust_fraud, sec_17_dormancy, sec_18_mongo, sec_19_neo4j,
    sec_20_alteryx, sec_21_powerbi,
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--section", type=int, help="run one checkpoint 1..21")
    ap.add_argument("--no-report", action="store_true", help="console only")
    ap.add_argument("--skip-cross-cutting", action="store_true")
    args = ap.parse_args()

    rep = Report()
    print("\n  FinSight — End-to-End Validation\n  " + "=" * 60)
    secs = [_SECTIONS[args.section - 1]] if args.section else _SECTIONS
    for fn in secs:
        print(f"\n  -- {fn.__doc__ or fn.__name__} --" if False else "")
        try:
            fn(rep)
        except Exception as exc:  # noqa: BLE001
            rep.add(fn.__name__, "checkpoint executed", "no exception",
                    f"{type(exc).__name__}: {exc}", "FAIL")
    if not args.section and not args.skip_cross_cutting:
        sec_cross_cutting(rep)

    c = rep.counts()
    print("\n  " + "=" * 60)
    print(f"  TOTAL {len(rep.rows)}  |  PASS {c['PASS']}  FAIL {c['FAIL']}  "
          f"BLOCKED {c['BLOCKED']}  WARN {c['WARN']}  SKIP {c['SKIP']}")
    print("  " + "=" * 60)

    if not args.no_report and not args.section:
        out = REPO / "docs" / "testing" / "E2E_REPORT.md"
        out.parent.mkdir(parents=True, exist_ok=True)
        rep.write_md(out)
        print(f"  report -> {out.relative_to(REPO)}")

    if c["FAIL"]:
        print(f"\n  {c['FAIL']} FAIL(s) - real defects. Review before any change.")
        return 1
    if c["BLOCKED"]:
        print(f"\n  {c['BLOCKED']} BLOCKED - run scripts/run_e2e_pipeline.sh to "
              "populate, then re-validate.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
